# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1297375449);
user_pref("app.update.lastUpdateTime.background-update-timer", 1297375883);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1297375720);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1297375806);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1297375786);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1297375631);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.13");
user_pref("extensions.enabledItems", "{CAFEEFAC-0016-0000-0023-ABCDEFFEDCBA}:6.0.23,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.13");
user_pref("extensions.lastAppVersion", "3.6.13");
user_pref("extensions.newAddons", false);
user_pref("extensions.update.notifyUser", false);
user_pref("idle.lastDailyNotification", 1297375368);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.last_vacuum", 1297375368);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("signon.rememberSignons", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1299459926);
